### PR TITLE
Update dev dependencies, select2, sass, material-icons, storybook

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Some extends weren't compatible with the newest sass version, including our bootstrap select 2 dependency, material icons wasn't up to date so it was missing some icons, stylelint was out of date
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | On storybook, the select2 part should look as before, the breadcrumb too, and the input type file too, material icons too, nothing should change inside the backoffice
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by matks — APPROVED** [review]
@NeOMakinG should these changes go into a new minor or major version of the UI Kit?

**Comment by NeOMakinG** [comment]
> @NeOMakinG should these changes go into a new minor or major version of the UI Kit?

Minor, it doesn't add any BC, and should work with previous versions of node-sass, sass or whatever sass library

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@NeOMakinG what now? should QA test it?

**Comment by NeOMakinG** [comment]
@kpodemski I seen with @florine2623 she should be able to test the sensible points of this PR :)

**Review by FabienPapet — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @florine2623 and @NeOMakinG

**Pull request merged**
