### PR TITLE
Remove modal border

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | There was a border we don't want on modals
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28162.
| How to test?      | Use the local PR branch as a `prestakit` dependency in prestashop, then check if the border disappeared anywhere in the BO, you can also run `npm i && npm run storybook` on this branch and check the modal directly inside it!
| Possible impacts? | Modal borders

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]
@NeOMakinG Do we test by QA or by dev on the UI Kit?

**Comment by NeOMakinG** [comment]
> @NeOMakinG Do we test by QA or by dev on the UI Kit?

Both looks fine to me, it's an easy test

**Review by florine2623 — COMMENTED** [review]
Hello @NeOMakinG ,

On storybook and on the prestakit, it looks good.
 
Screenshot 2022-10-25 at 10 14 25
Screenshot 2022-10-25 at 10 15 27

But on my BO, it is different (develop and 8.0.x branches)
I still have the border and in the modal there's another block. I don't think it should be there.
Screenshot 2022-10-25 at 10 16 50

I might not be testing it the right way 😅 
I have installed `prestashop-ui-kit` directly in my shop.

Can you let me know if that's the right way to do it ? ^^
Thanks!

**Comment by NeOMakinG** [comment]
@florine2623 I think you missed something while testing, ping me when you're ready to test it again

**Review by florine2623 — APPROVED** [review]
Hello @NeOMakinG ,

It is validated, thanks !!
Screenshot 2022-10-28 at 10 01 23

It is QA ✅

**Pull request merged**
