### PR TITLE
Add black color to warning and light buttons

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Basics buttons warning and lights needed to have a gray color
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/prestashop-ui-kit/issues/165.
| How to test?      | Run storybook and see Buttons => Basics colors on warning/light
| Possible impacts? | Basic buttons

# How does it looks?
image

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@PrestaShop/ux-team We need a validation on these colors

**Review by PierreRambaud — APPROVED** [review]

**Comment by prestascott** [comment]
@NeOMakinG Is the color used #363a41?

**Comment by NeOMakinG** [comment]
> 363A41

Exactly!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sarahdib

**Pull request merged**
