### PR TITLE
Add SCSS variables to storybook

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | External users had no way of reading SCSS variables without having the repository opened, now it's automatically updated inside storybook
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | `npm run storybook` and read variables section

image
image

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Can be tested by dev I think :)

**Comment by Progi1984** [comment]
> @PierreRambaud : 
> Can be tested by dev I think :)

@PrestaShop/qa-functional : OK for a QA Dev ?

**Comment by NeOMakinG** [comment]
I agree, it should be fine :)

**Comment by Robin-Fischer-PS** [comment]
@NeOMakinG @Progi1984 OK for QA by dev, thanks :)

**Comment by NeOMakinG** [comment]
Thanks for testing @PierreRambaud

**Pull request merged**
