### PR TITLE
Improvement: Updates focus state for buttons

### PR DESCRIPTION
**Pull request by amaury-hanser**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Updates the focus style for buttons
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Run storybook and try to focus button on _buttons basic, buttons outline and buttons group_
| Possible impacts? | It's only a visual change.

Hello, 

In order to have a better accessibility of PrestaShop, 
I suggest to add a visible `:focus` state to the buttons.

This PR updates:
- `scss/mixins/_buttons.scss`   
  - removes: `box-shadow: none`
  - updates: `color`, `background-color` and `border-color` to use the same as the one for the `:hover` state
- `_buttons.scss`
  - uses same `border-color` for `:focus` and `:hover` state

Sample:

image

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@PrestaShop/ux-team waiting for your validation :)

**Review by NeOMakinG — APPROVED** [review]
Looks fine to me 👍

**Comment by amaury-hanser** [comment]
I'd like to add that:   
**It will only affect plain, outlined and group buttons.**  

Invisible buttons won't be affected, I do believe that _they need an update too_, but the styling choice was less obvious so I did nothing about them.

**Comment by prestascott** [comment]
Hello @amaury-hanser,

Thanks for your PR, as we discussed i'm ok with that. But i'm not so sure about the color of the focus used on each button. It doesn't really help users identify the focused component. This is why using the same color for the focus border will be better because of the contrast. Wdyt?

**Comment by NeOMakinG** [comment]
@amaury-hanser 

@prestascott suggest this on EVERY buttons, with the primary color outlining any buttons

    outline-offset: 4px;
    outline: 2px solid $primary;
    outline-style: auto;

**Comment by NeOMakinG** [comment]
> > @amaury-hanser
> > @prestascott suggest this on EVERY buttons, with the primary color outlining any buttons
> > ```
> > outline-offset: 4px;
> > outline: 2px solid $primary;
> > outline-style: auto;
> > ```
> 
> I don't believe that `outline` has a radius property, if we use `outline`, we'll get a square. Would that be ok ?

outline-style: auto; makes it following the radius of the button, but it won't be supported by old browsers, and it looks ok for it :)

**Comment by amaury-hanser** [comment]
> > > @amaury-hanser
> > > @prestascott suggest this on EVERY buttons, with the primary color outlining any buttons
> > > ```
> > > outline-offset: 4px;
> > > outline: 2px solid $primary;
> > > outline-style: auto;
> > > ```
> > 
> > 
> > I don't believe that `outline` has a radius property, if we use `outline`, we'll get a square. Would that be ok ?
> 
> outline-style: auto; makes it following the radius of the button, but it won't be supported by old browsers, and it looks ok for it :)

You mean in the latest version of Chrome on Ubuntu ? ^^

I'm testing the change, and it won't work on Storybook.  
My guess is that Bootstrap is loaded after the UI-Kit and it messes with the outline, but I'm not sure.

This is the problematic rule:
```
button:focus:not(:focus-visible) {
    outline: 0;
}
```
Any idea where it comes from?

**Comment by NeOMakinG** [comment]
Looks like bootstrap _reboot partials is overriding it on `button` selector, can't we deal with a better selector in order to override it? It looks like we should be able to do it

**Comment by amaury-hanser** [comment]
This would do the trick, but if feels dirty:
```
    &:focus, 
    &:focus:not(.focus-visible) { ... }
```

**Comment by amaury-hanser** [comment]
Ok, fine for the selector.  

In Firefox, the outline is red, I'm investigating to find why because I don't see any rules overwriting the `outline-color`.  
If I add `!important` it's working, but I'm trying to understand where the red comes from.

**Comment by NeOMakinG** [comment]
Did you find it out @amaury-hanser? Overwise, I'll take a look

**Comment by amaury-hanser** [comment]
> Did you find it out @amaury-hanser? Overwise, I'll take a look

Hello, no sorry, I hadn't much time to investigate further.  
The outline is red in Firefox, I couldn't find why as there is no rule setting it to red.

**Comment by Progi1984** [comment]
@amaury-hanser & @NeOMakinG Stylelint disagrees with you :wink:

**Comment by NeOMakinG** [comment]
good @Progi1984 , sorry :P

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @amaury-hanser & @sarahdib

**Pull request merged**
