### PR TITLE
Export every methods of the UIKit

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | In case you need to run a little method after the initial init, you are not able to do it on every part of the UIKit, this PR makes this possible
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try to use window.prestaShopUiKit.initNumbers(); in the console for example, the object should be accessible in the console but the method should return undefined
| Possible impacts? | Nothing touchy

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG When I try using Develop 
Capture d’écran 2021-02-03 à 18 27 53

Using UI KIT
Capture d’écran 2021-02-03 à 18 21 54

**Comment by NeOMakinG** [comment]
image

Looks fine to me, did you `rm -rf node_modules && npm i && npm run build` on new-theme folder ?

I'm rebasing this PR anyway as it contains conflicts

**Comment by PierreRambaud** [comment]
> image
> 
> Looks fine to me, did you `rm -rf node_modules && npm i && npm run build` on new-theme folder ?
> 
> I'm rebasing this PR anyway as it contains conflicts

It was maybe because of conflicts files ;)

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG my bad this should be used when we are in a migrated page :) it's ok now for me :)

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sarahdib

**Pull request merged**
