### PR TITLE
Update storybook to 6.2.8, remove console log and update stylelint-config

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try to run `npm run storybook` and see if everything looks well, also try to use `npm run build-storybook` without any errors

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG 
When I use npm run build-storybook : 
Capture d’écran 2021-04-20 à 08 47 11

Capture d’écran 2021-04-20 à 08 46 59

When I use npm run storybook
Capture d’écran 2021-04-20 à 08 48 05

**Comment by NeOMakinG** [comment]
@sarahdib, please remove your node_folder before, then `npm i && npm run storybook`

**Comment by NeOMakinG** [comment]
@sarahdib, please remove your node_folder before, then `npm i && npm run storybook`

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sarahdib

**Pull request merged**
