### PR TITLE
Add nowrap to button as a dropdown-item

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Buttons as a dropdown-items are going at the line instead of extending the dropdown width
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [26714](https://github.com/PrestaShop/PrestaShop/pull/26714#issuecomment-987724997)
| How to test?      | Add the UIKit as a local path instead of the node_module inside the package.json of new-theme and see the last comment of the PR
| Possible impacts? | Dropdowns

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@NeOMakinG I add the Waiting for QA label but I don't know if they are able to test it easily :thinking:

**Comment by NeOMakinG** [comment]
> @NeOMakinG I add the Waiting for QA label but I don't know if they are able to test it easily 🤔

@sarahdib should be able to explain it, or just ping me, it's easily testable by changing the new-theme path to a local uikit folder, you can also see on other PRs where I explicitly explained it (I think we should add it to the default message of a PR)

**Comment by sarahdib** [comment]
@PierreRambaud don't worry :) we have a documentation based on the explanations made by @NeOMakinG  on the others PR

**Comment by PierreRambaud** [comment]
Thank you @sarahdib and @NeOMakinG

**Pull request merged**
