### PR TITLE
Export all init methods

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by sowbiba** [comment]
@NeOMakinG OK for you ?

**Comment by NeOMakinG** [comment]
@sowbiba nop, it should be on the develop branch, but I'm ok with the global idea

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Should be rebased on develop

Maybe I'll do it on another PR

**Comment by NeOMakinG** [comment]
Closing in favor of https://github.com/PrestaShop/prestashop-ui-kit/pull/133 as there are no news and more methods are needed

**Pull request closed without merging**
