### PR TITLE
Change helpbox positioning style to avoid line break

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Helpbox were returning to line on certain pages
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21843
| How to test?  | See issue (you should install the uikit locally on prestashop project)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Please rebase

**Comment by NeOMakinG** [comment]
Gonna rebase when https://github.com/PrestaShop/prestashop-ui-kit/pull/117 is merged

**Comment by Progi1984** [comment]
Next

**Comment by NeOMakinG** [comment]
done @Progi1984

**Comment by Progi1984** [comment]
Thanks @NeOMakinG

**Pull request merged**
