### PR TITLE
Show switch even is no inputs are checked

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Switch inputs were not visible if no inputs were checked
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21842.
| How to test?  | Add the UIKit locally in the new-theme path, see if the issue is resolved

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
The fix work only for currency page @NeOMakinG

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Please rebase

**Comment by NeOMakinG** [comment]
@Progi1984 done

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sarahdib

**Pull request merged**
