### PR TITLE
Add release CI to publish on npm

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This aim to publish on npm when a release is created, we also need to setup a token on this repository 
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Nothing testable

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
We have to create a token not related to a maintainer account before merging it

**Review by sowbiba — COMMENTED** [review]
LGTM

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I block this PR until we have a valid NPM_TOKEN :)

**Comment by NeOMakinG** [comment]
@PierreRambaud Keep it blocked until @eternoendless tell me that prestashopdevs got the rights!

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
