### PR TITLE
Fixes select2 hover and adjust border width

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Select2 hover was wrong when using optgroup, also the border-top color was wrong due to order of css attributes
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21836.
| How to test?  | Change you'r uikit path on new-theme of prestashop, rm -rf node_modules && npm i && npm run build, then go on translation page (see the issue) and check the hover of select2

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Please rebase

**Comment by NeOMakinG** [comment]
Gonna rebase when https://github.com/PrestaShop/prestashop-ui-kit/pull/116 is merged

**Comment by Progi1984** [comment]
@NeOMakinG Done

**Comment by NeOMakinG** [comment]
@Progi1984 done

**Comment by NeOMakinG** [comment]
@Progi1984 done

**Comment by Progi1984** [comment]
Thanks @NeOMakinG

**Pull request merged**
